# Lista de clústeres Infinispan
datagridClusters:
  - enabled: true
    name: datagrid
    version: 8.4.4-1
    replicas: 1
    labels:
      rht.comp: Data_Grid
      rht.comp_ver: 8.4.4
      rht.prod_name: Red_Hat_Runtimes
      rht.prod_ver: 2023-Q3
      rht.subcomp_t: application
    security:
      endpointAuthentication: true
      endpointEncryption:
        certSecretName: datagrid-cert-secret
        certServiceName: service.beta.openshift.io
        clientCert: None
        type: Service
      endpointSecretName: datagrid-generated-secret
    container:
      memory: '5Gi:3Gi'
    expose:
      type: Route
    scheduling:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: infinispan-pod
                    clusterName: datagrid
                    infinispan_cr: datagrid
                topologyKey: kubernetes.io/hostname
              weight: 100
    service:
      container:
        storage: 15Gi
      type: DataGrid
    jmx: {}
    configListener:
      enabled: true
      logging:
        level: info
    upgrades:
      type: Shutdown
    version: 8.4.4-1
    replicas: 5

# Lista de cachés vivas en OpenShift
caches:
  - enabled: true
    name: info-user-cache
    clusterName: datagrid
    template: |
      distributedCache:
        owners: 2
        mode: ASYNC
        statistics: true
        encoding:
          key:
            mediaType: application/octet-stream
          value:
            mediaType: application/octet-stream
        locking:
          concurrencyLevel: 128
          acquireTimeout: 500
        expiration:
          lifespan: 3610000 
          maxIdle: 3605000
        memory:
          storage: OFF_HEAP
          maxSize: 512MB
          whenFull: REMOVE
        persistence:
          passivation: true
          fileStore:
            shared: false
    updates:
      strategy: retain
  - enabled: true
    name: respCache
    clusterName: datagrid
    template: |
      distributedCache: 
        owners: "3"
        mode: "ASYNC"
        statistics: "true"
        encoding: 
          key: 
            mediaType: "application/octet-stream"
          value: 
            mediaType: "application/octet-stream"
        expiration: 
          lifespan: "21600000"
          interval: "60000"
        memory: 
          storage: "OFF_HEAP"
          maxSize: "3GB"
          whenFull: "REMOVE"
        persistence: 
          passivation: "false"
          fileStore: 
            shared: "false"
            data: 
              path: "user_type/data"
            index: 
              path: "user_type/index"
            writeBehind: 
              modificationQueueSize: "8192"
        stateTransfer: 
          awaitInitialTransfer: "false"
    updates:
      strategy: retain
